-- Meu Treino v12: banco real de exercícios + compatibilidade com o app.
-- Execute este arquivo UMA vez no SQL Editor do Supabase. Pode ser reexecutado com segurança.

alter table public.exercises add column if not exists slug text;
alter table public.exercises add column if not exists description text;
alter table public.exercises add column if not exists muscle_group text;
alter table public.exercises add column if not exists secondary_muscles text;
alter table public.exercises add column if not exists movement_type text;
alter table public.exercises add column if not exists difficulty text;
alter table public.exercises add column if not exists exercise_type text;
alter table public.exercises add column if not exists instructions text;
alter table public.exercises add column if not exists image_url text;
alter table public.exercises add column if not exists video_url text;
alter table public.exercises add column if not exists active boolean not null default true;
alter table public.exercises add column if not exists is_official boolean not null default false;

create unique index if not exists exercises_official_slug_uq on public.exercises(slug) where is_official=true;
create unique index if not exists exercise_videos_user_exercise_uq on public.exercise_videos(user_id,exercise_id);

update public.exercises set muscle_group=coalesce(muscle_group,group_name), active=coalesce(active,true);

insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Supino máquina','supino-maquina','Peito','Peito','Peitoral','','Máquinas','Iniciante','musculacao','empurrar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='supino-maquina' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Supino reto com barra','supino-reto-com-barra','Peito','Peito','Peitoral','','Barras','Iniciante','musculacao','empurrar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='supino-reto-com-barra' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Supino inclinado com barra','supino-inclinado-com-barra','Peito','Peito','Peitoral','','Barras','Iniciante','musculacao','empurrar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='supino-inclinado-com-barra' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Supino inclinado com halteres','supino-inclinado-com-halteres','Peito','Peito','Peitoral','','Halteres','Iniciante','musculacao','empurrar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='supino-inclinado-com-halteres' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Supino reto com halteres','supino-reto-com-halteres','Peito','Peito','Peitoral','','Halteres','Iniciante','musculacao','empurrar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='supino-reto-com-halteres' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Crucifixo máquina','crucifixo-maquina','Peito','Peito','Peitoral','','Máquinas','Iniciante','musculacao','empurrar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='crucifixo-maquina' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Crucifixo com halteres','crucifixo-com-halteres','Peito','Peito','Peitoral','','Halteres','Iniciante','musculacao','empurrar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='crucifixo-com-halteres' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Crossover na polia','crossover-na-polia','Peito','Peito','Peitoral','','Polias','Iniciante','musculacao','empurrar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='crossover-na-polia' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Peck deck','peck-deck','Peito','Peito','Peitoral','','Barras','Iniciante','musculacao','empurrar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='peck-deck' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Flexão de braços','flexao-de-bracos','Peito','Peito','Peitoral','','Peso corporal','Iniciante','musculacao','empurrar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='flexao-de-bracos' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Puxada frontal','puxada-frontal','Costas','Costas','Dorsais e romboides','','Barras','Iniciante','musculacao','puxar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='puxada-frontal' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Puxada neutra','puxada-neutra','Costas','Costas','Dorsais e romboides','','Barras','Iniciante','musculacao','puxar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='puxada-neutra' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Remada baixa na polia','remada-baixa-na-polia','Costas','Costas','Dorsais e romboides','','Polias','Iniciante','musculacao','puxar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='remada-baixa-na-polia' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Remada curvada com barra','remada-curvada-com-barra','Costas','Costas','Dorsais e romboides','','Barras','Iniciante','musculacao','puxar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='remada-curvada-com-barra' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Remada unilateral com halter','remada-unilateral-com-halter','Costas','Costas','Dorsais e romboides','','Halteres','Iniciante','musculacao','puxar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='remada-unilateral-com-halter' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Remada máquina articulada','remada-maquina-articulada','Costas','Costas','Dorsais e romboides','','Máquinas','Iniciante','musculacao','puxar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='remada-maquina-articulada' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Pulldown na polia','pulldown-na-polia','Costas','Costas','Dorsais e romboides','','Polias','Iniciante','musculacao','puxar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='pulldown-na-polia' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Pullover na polia','pullover-na-polia','Costas','Costas','Dorsais e romboides','','Polias','Iniciante','musculacao','puxar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='pullover-na-polia' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Barra fixa','barra-fixa','Costas','Costas','Dorsais e romboides','','Peso corporal','Iniciante','musculacao','puxar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='barra-fixa' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Remada cavalinho','remada-cavalinho','Costas','Costas','Dorsais e romboides','','Barras','Iniciante','musculacao','puxar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='remada-cavalinho' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Desenvolvimento na máquina','desenvolvimento-na-maquina','Ombros','Ombros','Deltoides','','Máquinas','Iniciante','musculacao','empurrar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='desenvolvimento-na-maquina' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Desenvolvimento com halteres','desenvolvimento-com-halteres','Ombros','Ombros','Deltoides','','Halteres','Iniciante','musculacao','empurrar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='desenvolvimento-com-halteres' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Desenvolvimento com barra','desenvolvimento-com-barra','Ombros','Ombros','Deltoides','','Barras','Iniciante','musculacao','empurrar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='desenvolvimento-com-barra' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Elevação lateral com halteres','elevacao-lateral-com-halteres','Ombros','Ombros','Deltoides','','Halteres','Iniciante','musculacao','empurrar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='elevacao-lateral-com-halteres' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Elevação lateral na polia','elevacao-lateral-na-polia','Ombros','Ombros','Deltoides','','Polias','Iniciante','musculacao','empurrar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='elevacao-lateral-na-polia' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Elevação frontal com halteres','elevacao-frontal-com-halteres','Ombros','Ombros','Deltoides','','Halteres','Iniciante','musculacao','empurrar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='elevacao-frontal-com-halteres' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Crucifixo inverso máquina','crucifixo-inverso-maquina','Ombros','Ombros','Deltoides','','Máquinas','Iniciante','musculacao','empurrar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='crucifixo-inverso-maquina' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Face pull','face-pull','Ombros','Ombros','Deltoides','','Polias','Iniciante','musculacao','empurrar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='face-pull' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Rosca direta com barra','rosca-direta-com-barra','Bíceps','Bíceps','Bíceps','','Barras','Iniciante','musculacao','puxar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='rosca-direta-com-barra' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Rosca direta com halteres','rosca-direta-com-halteres','Bíceps','Bíceps','Bíceps','','Halteres','Iniciante','musculacao','puxar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='rosca-direta-com-halteres' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Rosca alternada','rosca-alternada','Bíceps','Bíceps','Bíceps','','Barras','Iniciante','musculacao','puxar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='rosca-alternada' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Rosca martelo','rosca-martelo','Bíceps','Bíceps','Bíceps','','Barras','Iniciante','musculacao','puxar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='rosca-martelo' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Rosca Scott','rosca-scott','Bíceps','Bíceps','Bíceps','','Barras','Iniciante','musculacao','puxar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='rosca-scott' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Rosca concentrada','rosca-concentrada','Bíceps','Bíceps','Bíceps','','Barras','Iniciante','musculacao','puxar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='rosca-concentrada' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Rosca na polia baixa','rosca-na-polia-baixa','Bíceps','Bíceps','Bíceps','','Polias','Iniciante','musculacao','puxar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='rosca-na-polia-baixa' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Tríceps na polia com corda','triceps-na-polia-com-corda','Tríceps','Tríceps','Tríceps','','Polias','Iniciante','musculacao','empurrar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='triceps-na-polia-com-corda' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Tríceps na polia com barra','triceps-na-polia-com-barra','Tríceps','Tríceps','Tríceps','','Polias','Iniciante','musculacao','empurrar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='triceps-na-polia-com-barra' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Tríceps francês com halter','triceps-frances-com-halter','Tríceps','Tríceps','Tríceps','','Halteres','Iniciante','musculacao','empurrar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='triceps-frances-com-halter' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Tríceps testa com barra','triceps-testa-com-barra','Tríceps','Tríceps','Tríceps','','Barras','Iniciante','musculacao','empurrar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='triceps-testa-com-barra' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Tríceps unilateral na polia','triceps-unilateral-na-polia','Tríceps','Tríceps','Tríceps','','Polias','Iniciante','musculacao','empurrar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='triceps-unilateral-na-polia' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Mergulho assistido','mergulho-assistido','Tríceps','Tríceps','Tríceps','','Barras','Iniciante','musculacao','empurrar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='mergulho-assistido' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Tríceps máquina','triceps-maquina','Tríceps','Tríceps','Tríceps','','Máquinas','Iniciante','musculacao','empurrar', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='triceps-maquina' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Leg press 45°','leg-press-45','Quadríceps','Quadríceps','Quadríceps','','Máquinas','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='leg-press-45' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Agachamento no Smith','agachamento-no-smith','Quadríceps','Quadríceps','Quadríceps','','Barras','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='agachamento-no-smith' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Agachamento livre','agachamento-livre','Quadríceps','Quadríceps','Quadríceps','','Barras','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='agachamento-livre' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Cadeira extensora','cadeira-extensora','Quadríceps','Quadríceps','Quadríceps','','Máquinas','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='cadeira-extensora' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Hack squat','hack-squat','Quadríceps','Quadríceps','Quadríceps','','Máquinas','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='hack-squat' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Afundo no Smith','afundo-no-smith','Quadríceps','Quadríceps','Quadríceps','','Barras','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='afundo-no-smith' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Passada com halteres','passada-com-halteres','Quadríceps','Quadríceps','Quadríceps','','Halteres','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='passada-com-halteres' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Cadeira flexora','cadeira-flexora','Posterior de coxa','Posterior de coxa','Isquiotibiais','','Máquinas','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='cadeira-flexora' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Mesa flexora','mesa-flexora','Posterior de coxa','Posterior de coxa','Isquiotibiais','','Máquinas','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='mesa-flexora' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Stiff com halteres','stiff-com-halteres','Posterior de coxa','Posterior de coxa','Isquiotibiais','','Halteres','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='stiff-com-halteres' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Stiff com barra','stiff-com-barra','Posterior de coxa','Posterior de coxa','Isquiotibiais','','Barras','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='stiff-com-barra' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Levantamento terra romeno','levantamento-terra-romeno','Posterior de coxa','Posterior de coxa','Isquiotibiais','','Barras','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='levantamento-terra-romeno' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Flexão nórdica','flexao-nordica','Posterior de coxa','Posterior de coxa','Isquiotibiais','','Peso corporal','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='flexao-nordica' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Hip thrust','hip-thrust','Glúteos','Glúteos','Glúteos','','Barras','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='hip-thrust' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Glute bridge','glute-bridge','Glúteos','Glúteos','Glúteos','','Barras','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='glute-bridge' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Cadeira abdutora','cadeira-abdutora','Glúteos','Glúteos','Glúteos','','Máquinas','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='cadeira-abdutora' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Coice na polia','coice-na-polia','Glúteos','Glúteos','Glúteos','','Polias','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='coice-na-polia' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Agachamento sumô','agachamento-sumo','Glúteos','Glúteos','Glúteos','','Barras','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='agachamento-sumo' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Afundo búlgaro','afundo-bulgaro','Glúteos','Glúteos','Glúteos','','Barras','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='afundo-bulgaro' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Cadeira adutora','cadeira-adutora','Adutores','Adutores','Adutores','','Máquinas','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='cadeira-adutora' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Adução na polia','aducao-na-polia','Adutores','Adutores','Adutores','','Polias','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='aducao-na-polia' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Agachamento sumô','agachamento-sumo','Adutores','Adutores','Adutores','','Barras','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='agachamento-sumo' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Panturrilha em pé na máquina','panturrilha-em-pe-na-maquina','Panturrilhas','Panturrilhas','Gastrocnêmio e sóleo','','Máquinas','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='panturrilha-em-pe-na-maquina' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Panturrilha sentada','panturrilha-sentada','Panturrilhas','Panturrilhas','Gastrocnêmio e sóleo','','Barras','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='panturrilha-sentada' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Panturrilha no leg press','panturrilha-no-leg-press','Panturrilhas','Panturrilhas','Gastrocnêmio e sóleo','','Máquinas','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='panturrilha-no-leg-press' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Panturrilha unilateral','panturrilha-unilateral','Panturrilhas','Panturrilhas','Gastrocnêmio e sóleo','','Barras','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='panturrilha-unilateral' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Abdominal máquina','abdominal-maquina','Abdômen','Abdômen','Core','','Máquinas','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='abdominal-maquina' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Abdominal na polia','abdominal-na-polia','Abdômen','Abdômen','Core','','Polias','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='abdominal-na-polia' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Elevação de pernas','elevacao-de-pernas','Abdômen','Abdômen','Core','','Peso corporal','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='elevacao-de-pernas' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Prancha','prancha','Abdômen','Abdômen','Core','','Peso corporal','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='prancha' and e.is_official=true);
insert into public.exercises (name,slug,group_name,muscle_group,muscles,secondary_muscles,equipment,difficulty,exercise_type,movement_type,description,instructions,image_url,video_url,is_official,active) select 'Pallof press','pallof-press','Abdômen','Abdômen','Core','','Barras','Iniciante','musculacao','membros inferiores', 'Exercício oficial do banco Meu Treino.','Execute com controle, amplitude confortável e técnica consistente.',null,null,true,true where not exists (select 1 from public.exercises e where e.slug='pallof-press' and e.is_official=true);

drop policy if exists "official_exercises_read" on public.exercises;
create policy "official_exercises_read" on public.exercises for select using (is_official=true or user_id=auth.uid());

grant select on public.exercises to anon, authenticated;
-- Corrige as políticas de propriedade sem depender de uma coluna id inexistente em user_snapshots.
do $$ declare t text; begin
for t in select unnest(array['user_snapshots','exercises','exercise_videos','workouts','workout_sessions','weight_records','cardio_records','photos','favorites','ai_conversations','ai_generated_workouts','trash','audit_logs','settings']) loop
  execute format('drop policy if exists "owner_select" on public.%I',t);
  execute format('drop policy if exists "owner_insert" on public.%I',t);
  execute format('drop policy if exists "owner_update" on public.%I',t);
  execute format('drop policy if exists "owner_delete" on public.%I',t);
  execute format('create policy "owner_select" on public.%I for select using (user_id = auth.uid())',t);
  execute format('create policy "owner_insert" on public.%I for insert with check (user_id = auth.uid())',t);
  execute format('create policy "owner_update" on public.%I for update using (user_id = auth.uid()) with check (user_id = auth.uid())',t);
  execute format('create policy "owner_delete" on public.%I for delete using (user_id = auth.uid())',t);
end loop;
end $$;

drop policy if exists "owner_select" on public.profiles;
drop policy if exists "owner_insert" on public.profiles;
drop policy if exists "owner_update" on public.profiles;
drop policy if exists "owner_delete" on public.profiles;
create policy "owner_select" on public.profiles for select using (id = auth.uid());
create policy "owner_insert" on public.profiles for insert with check (id = auth.uid());
create policy "owner_update" on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());
create policy "owner_delete" on public.profiles for delete using (id = auth.uid());
